### ISSUE TITLE
URL error? Cannot open connection

### ISSUE THREAD

**Issue by jonesor** [ropensci/geonames#13]
GNcountryCode gives a URL error (after a long while trying).

```
> geonames::GNcountryCode(45, -123)
Error in url(url, open = "r") : cannot open the connection
```

**Comment by barryrowlingson** [comment]
Hmm. Nothing seems to be working for me...

Have geonames changed their host name or something? The default host is:

```
> options()$geonamesHost
[1] "ws.geonames.org"
```

but the examples on the web use `api.geonames.org`. Set this and it seems to work.

```
> options(geonamesHost="api.geonames.org")
> GNtimezone(lat=47, lng=10.2)
           sunrise  lng countryCode gmtOffset rawOffset           sunset
1 2016-05-10 05:49 10.2          AT         1         1 2016-05-10 20:42
     timezoneId dstOffset countryName             time lat
1 Europe/Vienna         2     Austria 2016-05-10 13:32  47
```

and your example:

```
> geonames::GNcountryCode(45, -123)
$languages
[1] "en-US,es-US,haw,fr"

$distance
[1] "0"

$countryName
[1] "United States"

$countryCode
[1] "US"
```

I don't know if this is a temporary glitch with ws.geonames.org, or whether ws.geonames.org is now deprecated and I should change the default...

**Comment by barryrowlingson** [comment]
https://sourceforge.net/p/geotag/bugs/33/ says its deprecated, and I guess they closed it. I'll fix the default here.
