### ISSUE TITLE
Connection error for GNstrm3

### ISSUE THREAD

**Issue by markusdumke** [ropensci/geonames#16]
`GNsrtm3(lat=54,lng=-1)`

> Error in url(url, open = "r") : cannot open the connection
> In addition: Warning message:
> In url(url, open = "r") :
>   InternetOpenUrl failed: 'A connection with the server could not be established'

It seems that GNsrtm3 cannot connect to geonames anymore?

**Comment by joostbouten** [comment]
I believe I have the same problem, it seems as if the GN functions try to open the following type of urls:

http://ws.geonames.org/...

Where it perhaps should be:

http://api.geonames.org/...

I am not sure though..

**Comment by barryrowlingson** [comment]
geonames function connect to a host defined by `options()$geonamesHost` which is set on load to:  

      options(geonamesHost="api.geonames.org")

if the option isn't already set, at least in the current version on github. Perhaps you have a version from CRAN that used `ws.geonames.org`?

**Comment by joostbouten** [comment]
I do have the CRAN version indeed, thanks.

**Comment by barryrowlingson** [comment]
fixed in recent version just pushed to CRAN
