### ISSUE TITLE
Push new  version to CRAN

### ISSUE THREAD

**Issue by barryrowlingson** [ropensci/geonames#17]
The CRAN version now doesn't work because the geonames host has changed. Its been a while and I'm not so au fait with CRANpolicies, can anyone hold my hand for a new CRAN push? 

Are there other ropensci policies like tagging a release before submitting to CRAN?

Help or pointer to docs welcome.

**Comment by sckott** [comment]
We don't have a guide per se for going to cran, here's some thoughts though:

- good idea to use `devtools::release()` to submit cause it checks various things for you so you don't have to 
- please do git tag a release matching the version of the pkg you're sending to cran and put your news items for that version in the release notes 
- for checking which should raise any potential cran issues, options include: on your own machine, win builder (e.g., `devtools::build_win()`), travis, appveyor, rhub https://github.com/r-hub/rhub

**Comment by barryrowlingson** [comment]
All, done waiting on CRANdalf to let it pass...
