### ISSUE TITLE
Find out where a place is

### ISSUE THREAD

**Issue by Robinlovelace** [ropensci/geonames#8]
I've finally downloaded and installed geonames and it looks very useful.

Great that it can find post-codes, e.g.:

```
GNpostalCodeSearch(postalcode = "LS7 3HB")
```

However, I couldn't find out how to find the place ("Chapeltown, Leeds") in a way that is analogous to ggmap::geocode(), which seems to be broken!

Note - this is something also being looked at here:
https://github.com/hrbrmstr/overpass

Thanks.

**Comment by barryrowlingson** [comment]
`GNsearch(name="Chapeltown", country="UK")` returns a data frame of matches.

Best way to explore the package is to go to the geonames API docs:

http://www.geonames.org/export/ws-overview.html

then hit up a service doc page:

http://www.geonames.org/export/geonames-search.html

and then those parameters become your R function arguments to a geonames package function prefixed with "GN"...

Note it doesn't seem to find a Chapeltown in Leeds! There's a match in Sheffield. You can look up the hierarchy given the ID:

GNhierarchy(6952268)

**Comment by Robinlovelace** [comment]
Cheers for the clear explanation Barry - makes more sense now.

To help other noobs like me who download this I've added an example in the documentation which I'll submit as a PR. Hope this helps!
